name: optiparse
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  image_cropper: ^8.0.2
  gallery_picker: ^0.5.1
  image_picker: ^1.1.2
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true




  assets:
    - assets/bg.jpg
    - assets/done.json
    - assets/updated.json
    - assets/loading.json
